AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Style/OpenStructUse:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
