version: 2.1

update_bundler: &update_bundler
  run:
    name: update bundler
    command: gem update bundler

bundle_install: &bundle_install
  run:
    name: bundle install
    command: bundle install --path vendor/bundle --jobs 4

git statusrestore_bundle_cache: &restore_bundle_cache
  restore_cache:
    key: cache-bundler-{{ checksum "Gemfile.lock" }}

install_cmake: &install_cmake
  run:
    name: install cmake
    command: sudo apt-get install cmake

jobs:
  build:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - *install_cmake
      - *restore_bundle_cache
      - *update_bundler
      - *bundle_install
      - save_cache:
          key: cache-bundler-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
  rubocop:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - *install_cmake
      - *restore_bundle_cache
      - *update_bundler
      - *bundle_install
      - run: bundle exec rubocop
  rspec:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - *install_cmake
      - *restore_bundle_cache
      - *update_bundler
      - *bundle_install
      - run:
          environment:
            COVERAGE: true
            CODECOV_TOKEN: efe02ed0-e754-42a6-bb90-bbf345747bdc
          command: bundle exec rspec
workflows:
  version: 2.1
  rspec:
    jobs:
      - build
      - rubocop:
          requires: [build]
      - rspec:
          requires: [build]
