name: release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
jobs:
  push:
    name: Push gem to RubyGems.org
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: .ruby-version
      - name: Setup Git
        run: |
          git config --global user.email "unhappychoice@gmail.com"
          git config --global user.name "unhappychoice"
      - name: Install gem-release
        run: gem install gem-release
      - name: Bump version
        run: |
          gem bump --version ${{inputs.version}} --message ':tada: Bump %{name} to %{version}'
          bundle config set frozen false && bundle install
          git add . && git commit --amend --no-edit
      - uses: rubygems/release-gem@v1
