name: test

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
      - name: Install bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install --jobs 4
      - name: Run test
        run: bundle exec rubocop lib
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.4.4', '3.3.8', '3.2.8', '3.1.7']
    steps:
      - uses: actions/checkout@master
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Install bundler
        run: gem install bundler
      - name: Install dependencies
        run: bundle install --jobs 4
      - name: Run test
        env:
          COVERAGE: true
          CODECOV_TOKEN: efe02ed0-e754-42a6-bb90-bbf345747bdc
        run: bundle exec rspec
